# -*- coding: utf-8 -*-
"""configs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yx05o_mDFA9ICPx64JPoxfSxTNlpsKBW
"""

#------------------------------- Traing Settings -------------------------------#
SETTING= {
    "seed": 43,
    "learning_rate": 1e-4,
    "device": "cuda:0" if torch.cuda.is_available() else "cpu",
    "batch_size": 32,
    "weight_decay": 1e-4,
    "num_epochs": 70,
    "num_workers": 2,
    "pin_memory": True,
    "load_model": False,
    "load_model_file": "./drive/MyDrive/ResLSTM.path.tar",
    "patience": 10,
#    "feat_dir": directory of features
#    "label_dir": direct1ory of labels

}

torch.manual_seed(SETTING["seed"])

#------------------------------- Config -------------------------------#

INPUT_DIM = 39
NUM_CLASSES = 47

# feature extraction
# FRAME_SIZE = 160
# SR = 16000
# FRAME_RATE = int( sr / frame_size)
# NUM_MFCC = 13
# HOP_LENGTH = 40

# assert FRAME_SIZE % HOP_LENGTH == 0

# INPUT_DIM = int(NUM_MFCC * (FRAME_SIZE / HOP_LENGTH))

# dictionary
# IPAS = [] # token list
# IPAS = ['0', 'u'] + sorted(ipas) + ['-']
# NUM_CLASSES = len(ipas)

# MODEL_NAME = 'CRNN_CTC'